#!/usr/bin/env node
// Copies each tour's data out of the CityAnatomyAustin app and into the
// matching web app folder on this site, as plain script files the page can
// load with a <script> tag.
//
// WHY A COPY: anatomy.city is a static site with no build step, and the app
// repo is private. Each web app needs the same stops, routes, stories and map
// styles the phone app ships, so this script writes each JSON file as a
// global (`window.MT1885_STOPS = {...}`). Nothing in a vendor/ folder is
// edited by hand: change the data in the app, run this again.
//
//   node tools/sync-webapps.js
//
// The app's own generated files are the source (src/modules/<id>/data), the
// same ones the phone app imports, so the web apps can never drift from it.

const fs = require('fs');
const path = require('path');

const SITE = path.resolve(__dirname, '..');
// Sibling repo under the same GitHub account folder.
const APP = path.resolve(SITE, '..', 'CityAnatomyAustin');

// One entry per web app: which app module feeds it, the global-name prefix,
// which route legs to merge, and the extra JSON files to copy as
// [source file, global suffix, output file].
const APPS = [
  {
    folder: '1885murdertour',
    module: 'servantgirlmurdertour',
    prefix: 'MT1885',
    legs: ['core', 'extension', 'coda'],
    extra: [['stops-content.json', 'STORIES', 'stops-content.js']],
  },
  {
    folder: 'moontowertour',
    module: 'moontowertour',
    prefix: 'MOONTOWER',
    legs: ['downtown', 'east', 'south', 'hydepark', 'zilker'],
    extra: [],
  },
];

for (const app of APPS) {
  const data = path.join(APP, 'src', 'modules', app.module, 'data');
  if (!fs.existsSync(data)) {
    console.error('App data folder not found: ' + data);
    process.exit(1);
  }
  const out = path.join(SITE, app.folder, 'vendor');
  fs.mkdirSync(out, { recursive: true });

  const banner = (from) =>
    '// GENERATED by tools/sync-webapps.js from CityAnatomyAustin ' +
    app.module + '/data/' + from + ' - never hand-edit.\n';
  const write = (file, from, global, value) => {
    fs.writeFileSync(
      path.join(out, file),
      banner(from) + 'window.' + app.prefix + '_' + global + ' = ' + JSON.stringify(value) + ';\n'
    );
    console.log(app.folder + '/vendor/' + file);
  };
  const read = (from) => JSON.parse(fs.readFileSync(path.join(data, from), 'utf8'));

  write('stops.js', 'stops.json', 'STOPS', read('stops.json'));
  write('style-night.js', 'map-style.json', 'STYLE_NIGHT', read('map-style.json'));
  write('style-day.js', 'map-style-day.json', 'STYLE_DAY', read('map-style-day.json'));
  for (const [from, global, file] of app.extra) write(file, from, global, read(from));

  // The route legs become one collection, exactly as the app's tour-data does.
  const routes = { type: 'FeatureCollection', features: [] };
  for (const leg of app.legs) {
    const json = read('route-' + leg + '.json');
    routes.features.push(...(json.features || []));
  }
  write('routes.js', 'route-*.json (' + routes.features.length + ' segments)', 'ROUTES', routes);
}
